[package]
authors = ["Tyler Wolf Leonhardt <tyler.wolf.leonhardt@gmail.com>"]
description = "A library for registering errors."
exclude = [
    ".gitignore",
    "build.proj"
]
license = "MIT"
name = "graphy_error"
version = "0.2.0"
